from crewai import Crew,Process
from tasks import research_task,writer_task
from agents import news_researcher,news_writer
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

crew=Crew(
    agents=[news_researcher,news_writer],
    tasks=[research_task,writer_task],
    process=Process.sequential
)

#starting the task execution process with enhanced feedback

result=crew.kickoff()
print(result)

# Convert the result to a string (or any format you prefer)
result_str = str(result)  # or result.json() if result is a JSON object

# Email configuration
SMTP_SERVER = 'smtp.gmail.com'  # Replace with your SMTP server
SMTP_PORT = 587  # Replace with your SMTP port
SENDER_EMAIL = 'aishwaryak151194@gmail.com'  # Replace with your email address
SENDER_PASSWORD = 'uuobyrnpvorobdnl'  # Replace with your email password
RECEIVER_EMAIL = 'aishwaryakalburgi990@gmail.com'  # Replace with the recipient's email address

# Function to send an email with results attached
def send_email(subject, body, attachment_content, attachment_filename):
    # Create a multipart message
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject

    # Attach the body of the email
    msg.attach(MIMEText(body, 'plain'))

    # Attach the results file
    attachment = MIMEBase('application', 'octet-stream')
    attachment.set_payload(attachment_content.encode())
    encoders.encode_base64(attachment)
    attachment.add_header('Content-Disposition', f'attachment; filename={attachment_filename}')
    msg.attach(attachment)

    # Set up the server and send the email
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        print("Email sent successfully.")
    except Exception as e:
        print(f"Error sending email: {e}")
    finally:
        server.quit()

# Prepare the email subject and body
email_subject = "Daily News Summary Results"
email_body = "Attached are the results of today's news summary generated by CrewAI."

# Send the email with results attached
send_email(email_subject, email_body, result_str, "news_summary_results.txt")