name: Send News Summary

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC every day
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install chromadb==0.4.24
        pip install langchain-core==0.3.15
        pip install langchain==0.3.0
        pip install --no-deps crewai==0.41.1
        pip install --no-deps crewai-tools==0.4.26
        pip install python-dotenv==1.0.0
        pip install google-generativeai==0.8.1
        pip install langchain_google_genai==2.0.7
        pip install google-auth==2.27.0
        pip install mailchimp-marketing==3.0.80
        pip install markdown==3.5.2

    - name: Run script
      env:
        MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
        MAILCHIMP_SERVER_PREFIX: ${{ secrets.MAILCHIMP_SERVER_PREFIX }}
        LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      run: |
        cd crewOpenAI
        python crew.py


    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add new-blog-post.md
        git commit -m 'Update news content'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
